package fr.formation.projet.entities;
// Generated 2 sept. 2019 16:48:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clients generated by hbm2java
 */
@Entity
@Table(name = "clients", catalog = "pizza_db")
public class Clients implements java.io.Serializable {

	private Integer idClient;
	private String nom;
	private String prenom;
	private String adresse;
	private String numeroTel;
	private Set<Logistique> logistiques = new HashSet<Logistique>(0);
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public Clients() {
	}

	public Clients(String nom, String prenom, String adresse, String numeroTel, Set<Logistique> logistiques,
			Set<Commande> commandes) {
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.numeroTel = numeroTel;
		this.logistiques = logistiques;
		this.commandes = commandes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_client", unique = true, nullable = false)
	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	@Column(name = "nom", length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 30)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "adresse", length = 30)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "numero_tel", length = 15)
	public String getNumeroTel() {
		return this.numeroTel;
	}

	public void setNumeroTel(String numeroTel) {
		this.numeroTel = numeroTel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clients")
	public Set<Logistique> getLogistiques() {
		return this.logistiques;
	}

	public void setLogistiques(Set<Logistique> logistiques) {
		this.logistiques = logistiques;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clients")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
