package fr.formation.projet.entities;
// Generated 5 sept. 2019 12:27:01 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommandeArticleId generated by hbm2java
 */
@Embeddable
public class CommandeArticleId implements java.io.Serializable {

	private int idCommande;
	private int idArticle;
	private Integer articleQuantity;

	public CommandeArticleId() {
	}

	public CommandeArticleId(int idCommande, int idArticle) {
		this.idCommande = idCommande;
		this.idArticle = idArticle;
	}

	public CommandeArticleId(int idCommande, int idArticle, Integer articleQuantity) {
		this.idCommande = idCommande;
		this.idArticle = idArticle;
		this.articleQuantity = articleQuantity;
	}

	@Column(name = "ID_COMMANDE", nullable = false)
	public int getIdCommande() {
		return this.idCommande;
	}

	public void setIdCommande(int idCommande) {
		this.idCommande = idCommande;
	}

	@Column(name = "ID_ARTICLE", nullable = false)
	public int getIdArticle() {
		return this.idArticle;
	}

	public void setIdArticle(int idArticle) {
		this.idArticle = idArticle;
	}

	@Column(name = "ARTICLE_QUANTITY")
	public Integer getArticleQuantity() {
		return this.articleQuantity;
	}

	public void setArticleQuantity(Integer articleQuantity) {
		this.articleQuantity = articleQuantity;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommandeArticleId))
			return false;
		CommandeArticleId castOther = (CommandeArticleId) other;

		return (this.getIdCommande() == castOther.getIdCommande()) && (this.getIdArticle() == castOther.getIdArticle())
				&& ((this.getArticleQuantity() == castOther.getArticleQuantity())
						|| (this.getArticleQuantity() != null && castOther.getArticleQuantity() != null
								&& this.getArticleQuantity().equals(castOther.getArticleQuantity())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCommande();
		result = 37 * result + this.getIdArticle();
		result = 37 * result + (getArticleQuantity() == null ? 0 : this.getArticleQuantity().hashCode());
		return result;
	}

}
