package fr.formation.projet.entities;
// Generated 2 sept. 2019 16:48:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "commande", catalog = "pizza_db")
public class Commande implements java.io.Serializable {

	private Integer idCommande;
	private Clients clients;
	private String elementCmd;
	private String typeCmd;
	private Integer numTable;
	private BigDecimal montant;
	private Date heureCommande;
	private Set<Facturation> facturations = new HashSet<Facturation>(0);
	private Set<Logistique> logistiques = new HashSet<Logistique>(0);

	public Commande() {
	}

	public Commande(Clients clients, String elementCmd, String typeCmd, Integer numTable, BigDecimal montant,
			Date heureCommande, Set<Facturation> facturations, Set<Logistique> logistiques) {
		this.clients = clients;
		this.elementCmd = elementCmd;
		this.typeCmd = typeCmd;
		this.numTable = numTable;
		this.montant = montant;
		this.heureCommande = heureCommande;
		this.facturations = facturations;
		this.logistiques = logistiques;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_commande", unique = true, nullable = false)
	public Integer getIdCommande() {
		return this.idCommande;
	}

	public void setIdCommande(Integer idCommande) {
		this.idCommande = idCommande;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_client")
	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	@Column(name = "element_cmd", length = 30)
	public String getElementCmd() {
		return this.elementCmd;
	}

	public void setElementCmd(String elementCmd) {
		this.elementCmd = elementCmd;
	}

	@Column(name = "type_cmd", length = 30)
	public String getTypeCmd() {
		return this.typeCmd;
	}

	public void setTypeCmd(String typeCmd) {
		this.typeCmd = typeCmd;
	}

	@Column(name = "num_table")
	public Integer getNumTable() {
		return this.numTable;
	}

	public void setNumTable(Integer numTable) {
		this.numTable = numTable;
	}

	@Column(name = "montant", precision = 5)
	public BigDecimal getMontant() {
		return this.montant;
	}

	public void setMontant(BigDecimal montant) {
		this.montant = montant;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "heure_commande", length = 19)
	public Date getHeureCommande() {
		return this.heureCommande;
	}

	public void setHeureCommande(Date heureCommande) {
		this.heureCommande = heureCommande;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commande")
	public Set<Facturation> getFacturations() {
		return this.facturations;
	}

	public void setFacturations(Set<Facturation> facturations) {
		this.facturations = facturations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commande")
	public Set<Logistique> getLogistiques() {
		return this.logistiques;
	}

	public void setLogistiques(Set<Logistique> logistiques) {
		this.logistiques = logistiques;
	}

}
