package fr.formation.projet.entities;
// Generated 5 sept. 2019 14:31:58 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CommandeArticle generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "commande_article", catalog = "pizza_db")
public class CommandeArticle implements java.io.Serializable {

	private int idCommandeArticle;
	private Articles articles;
	private Commande commande;
	private Integer articleQuantity;

	public CommandeArticle() {
	}

	public CommandeArticle(int idCommandeArticle, Articles articles, Commande commande) {
		this.idCommandeArticle = idCommandeArticle;
		this.articles = articles;
		this.commande = commande;
	}

	public CommandeArticle(int idCommandeArticle, Articles articles, Commande commande, Integer articleQuantity) {
		this.idCommandeArticle = idCommandeArticle;
		this.articles = articles;
		this.commande = commande;
		this.articleQuantity = articleQuantity;
	}

	@Id

	@Column(name = "ID_COMMANDE_ARTICLE", unique = true, nullable = false)
	public int getIdCommandeArticle() {
		return this.idCommandeArticle;
	}

	public void setIdCommandeArticle(int idCommandeArticle) {
		this.idCommandeArticle = idCommandeArticle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ARTICLE", nullable = false)
	public Articles getArticles() {
		return this.articles;
	}

	public void setArticles(Articles articles) {
		this.articles = articles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_COMMANDE", nullable = false)
	public Commande getCommande() {
		return this.commande;
	}

	public void setCommande(Commande commande) {
		this.commande = commande;
	}

	@Column(name = "ARTICLE_QUANTITY")
	public Integer getArticleQuantity() {
		return this.articleQuantity;
	}

	public void setArticleQuantity(Integer articleQuantity) {
		this.articleQuantity = articleQuantity;
	}

}
