package fr.formation.projet.entities;
// Generated 5 sept. 2019 12:27:01 by Hibernate Tools 5.0.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CommandeArticle generated by hbm2java
 */
@Entity
@Table(name = "commande_article", catalog = "pizza_db")
public class CommandeArticle implements java.io.Serializable {

	private CommandeArticleId id;
	private Articles articles;
	private Commande commande;

	public CommandeArticle() {
	}

	public CommandeArticle(CommandeArticleId id, Articles articles, Commande commande) {
		this.id = id;
		this.articles = articles;
		this.commande = commande;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idCommande", column = @Column(name = "ID_COMMANDE", nullable = false)),
			@AttributeOverride(name = "idArticle", column = @Column(name = "ID_ARTICLE", nullable = false)),
			@AttributeOverride(name = "articleQuantity", column = @Column(name = "ARTICLE_QUANTITY")) })
	public CommandeArticleId getId() {
		return this.id;
	}

	public void setId(CommandeArticleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ARTICLE", nullable = false, insertable = false, updatable = false)
	public Articles getArticles() {
		return this.articles;
	}

	public void setArticles(Articles articles) {
		this.articles = articles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_COMMANDE", nullable = false, insertable = false, updatable = false)
	public Commande getCommande() {
		return this.commande;
	}

	public void setCommande(Commande commande) {
		this.commande = commande;
	}

}
