package fr.formation.projet.entities;
// Generated 2 sept. 2019 16:48:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Facturation generated by hbm2java
 */
@Entity
@Table(name = "facturation", catalog = "pizza_db")
public class Facturation implements java.io.Serializable {

	private Integer idFacture;
	private Commande commande;

	public Facturation() {
	}

	public Facturation(Commande commande) {
		this.commande = commande;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_facture", unique = true, nullable = false)
	public Integer getIdFacture() {
		return this.idFacture;
	}

	public void setIdFacture(Integer idFacture) {
		this.idFacture = idFacture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_commande")
	public Commande getCommande() {
		return this.commande;
	}

	public void setCommande(Commande commande) {
		this.commande = commande;
	}

}
