package fr.formation.projet.entities;
// Generated 5 sept. 2019 12:27:01 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Livreur generated by hbm2java
 */
@Entity
@Table(name = "livreur", catalog = "pizza_db")
public class Livreur implements java.io.Serializable {

	private Integer idLivreur;
	private String nom;
	private String mdp;
	private Set<Livraison> livraisons = new HashSet<Livraison>(0);

	public Livreur() {
	}

	public Livreur(String nom, String mdp, Set<Livraison> livraisons) {
		this.nom = nom;
		this.mdp = mdp;
		this.livraisons = livraisons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_LIVREUR", unique = true, nullable = false)
	public Integer getIdLivreur() {
		return this.idLivreur;
	}

	public void setIdLivreur(Integer idLivreur) {
		this.idLivreur = idLivreur;
	}

	@Column(name = "NOM", length = 30)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "MDP", length = 10)
	public String getMdp() {
		return this.mdp;
	}

	public void setMdp(String mdp) {
		this.mdp = mdp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "livreur")
	public Set<Livraison> getLivraisons() {
		return this.livraisons;
	}

	public void setLivraisons(Set<Livraison> livraisons) {
		this.livraisons = livraisons;
	}

}
