package fr.formation.projet.entities;
// Generated 2 sept. 2019 16:48:26 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Logistique generated by hbm2java
 */
@Entity
@Table(name = "logistique", catalog = "pizza_db")
public class Logistique implements java.io.Serializable {

	private Integer idLogistique;
	private Clients clients;
	private Commande commande;
	private Date heureDepart;
	private Date heureArrivee;
	private Date heureRetour;

	public Logistique() {
	}

	public Logistique(Clients clients, Commande commande) {
		this.clients = clients;
		this.commande = commande;
	}

	public Logistique(Clients clients, Commande commande, Date heureDepart, Date heureArrivee, Date heureRetour) {
		this.clients = clients;
		this.commande = commande;
		this.heureDepart = heureDepart;
		this.heureArrivee = heureArrivee;
		this.heureRetour = heureRetour;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_logistique", unique = true, nullable = false)
	public Integer getIdLogistique() {
		return this.idLogistique;
	}

	public void setIdLogistique(Integer idLogistique) {
		this.idLogistique = idLogistique;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_client", nullable = false)
	public Clients getClients() {
		return this.clients;
	}

	public void setClients(Clients clients) {
		this.clients = clients;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_commande", nullable = false)
	public Commande getCommande() {
		return this.commande;
	}

	public void setCommande(Commande commande) {
		this.commande = commande;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "heure_depart", length = 19)
	public Date getHeureDepart() {
		return this.heureDepart;
	}

	public void setHeureDepart(Date heureDepart) {
		this.heureDepart = heureDepart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "heure_arrivee", length = 19)
	public Date getHeureArrivee() {
		return this.heureArrivee;
	}

	public void setHeureArrivee(Date heureArrivee) {
		this.heureArrivee = heureArrivee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "heure_retour", length = 19)
	public Date getHeureRetour() {
		return this.heureRetour;
	}

	public void setHeureRetour(Date heureRetour) {
		this.heureRetour = heureRetour;
	}

}
